### ISSUE TITLE
What is the pytorch version?

### ISSUE THREAD

**Issue by ruizhaogit** [jimimvp/torch_rl#1]
Hi @jimimvp ,

Thank you for sharing the code!

I am trying to run the ddpg.py script, and run into the following error:

Traceback (most recent call last):
  File "examples/ddpg.py", line 7, in <module>
    from torch_rl.training import DDPGTrainer
  File "/home/z003rjch/workspace/hindsight-pg/torch_rl/training/__init__.py", line 3, in <module>
    from torch_rl.training.ppo import *
  File "/home/z003rjch/workspace/hindsight-pg/torch_rl/training/ppo.py", line 371, in <module>
    from torch_rl.models.ppo import ActorCriticPPO
  File "/home/z003rjch/workspace/hindsight-pg/torch_rl/models/ppo.py", line 4, in <module>
    from torch.distributions import Normal, Uniform
ImportError: cannot import name 'Uniform'

I am using pytorch 3.1. I think the error is due to different version of pytorch, so which one are you using?

Thanks!

Best,
Rui

**Comment by ruizhaogit** [comment]
Build pytorch from source solved the problem
